export const initialAppState = {
  teams: null,
  members: null,
  teamIndex: -1,
  secretIndex: -1,
  memberIndex: -1,
  secretDes: null,
  allDescriptions: null,
  allSecrets: null,
  selectedSecret: '',
  selectedSecretId: '',
  selectedDes: '',
  nameOpenDialog: '',
  username: '',
  selectedFileName: '',
};
